version: "3.8"
services:
  nats:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command:
      - "--js"
    networks:
      - local

  db:
    image: postgres:15.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - local

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - "./backing-services/prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - local
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./backing-services/datasources.yml:/etc/grafana/provisioning/datasources.yml
    networks:
      - local
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    restart: always

networks:
  local:
    driver: bridge

volumes:
  db:
    driver: local
